services:
  api:
    image: nicolasvienot/nesty-api:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      JWT_SECRET: "${JWT_SECRET}"
      FRONTEND_URL: "${FRONTEND_URL}"

  web:
    image: nicolasvienot/nesty-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - api

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - ~/caddy/data:/data
      - ~/caddy/config:/config
